export const UPDATE_SESSION = 'UPDATE_SESSION';
export const UPDATE_ACTIVITIES = 'UPDATE_ACTIVITIES';
export const UPDATE_DEVICES = 'UPDATE_DEVICES';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
